language: php

env:
  - DOCTRINE=default
  - DOCTRINE=~2.6
  - DOCTRINE=~2.5

php:
  - 7.1
  - 7.2

before_script:
  - php .travis.composer.php
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - composer ci