language: php

env:
  - NETTE=default
  - NETTE=~2.3.0
  - NETTE=~2.4.0

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - php .travis.composer.php
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/codecept run